version: "3.8"

services:
  uptime-dock:
    image: kushdhingra/uptime-dock:latest
    container_name: uptime-dock
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - uptime_data:/app/backend

volumes:
  uptime_data:
