version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: uptime
      POSTGRES_USER: uptimeuser
      POSTGRES_PASSWORD: uptimepass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - uptime-dock

  backend:
    build: ./backend
    networks:
      - uptime-dock

  frontend:
    build: ./frontend
    ports:
      - "3112:80"
    depends_on:
      - backend
    networks:
      - uptime-dock

volumes:
  pgdata:

networks:
  uptime-dock:
    driver: bridge

x-develop:
  backend:
    watch:
      - action: sync
        path: ./backend
        target: /app
      - action: rebuild
        path: ./backend/requirements.txt

  frontend:
    watch:
      - action: sync
        path: ./frontend
        target: /usr/share/nginx/html
      - action: rebuild
        path: ./frontend/package.json
