services:
  backend:
    build: ./backend
    networks:
      - uptime-dock

  frontend:
    build: ./frontend
    ports:
      - "3112:3112"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - uptime-dock

networks:
  uptime-dock:
    driver: bridge
