services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: uptime
      POSTGRES_USER: uptimeuser
      POSTGRES_PASSWORD: uptimepass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - uptime-dock

  backend:
    build: ./backend
    networks:
      - uptime-dock

  frontend:
    build: ./frontend
    ports:
      - "3112:3112"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - uptime-dock

volumes:
  pgdata:

networks:
  uptime-dock:
    driver: bridge
